apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-cdfvzwwt
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-cdfvzwwt:5e2b2671c94dd32c5020eb77c8554cf524d1f19e@sha256:2fb70f06ff33a284a890d0ed25e7202118a8cc85441e5e00ba783ecee1314937
          name: container-image
